// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CartAuthReq struct {
	CarPlate       string `json:"carPlate"`
	CarModel       string `json:"carModel"`
	DrivingLicense string `json:"drivingLicense"`
	Token          string `json:"token"`
}

type DriverAuthReq struct {
	RealName    string `json:"realName"`
	IDCard      string `json:"idCard"`
	IDCardFront string `json:"idCardFront"`
	IDCardBack  string `json:"idCardBack"`
	LicenseImg  string `json:"licenseImg"`
	Token       string `json:"token"`
}

type DriverLoginReq struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	DriverId int    `json:"driverId"`
}

type OutLoginReq struct {
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type SendSmsReq struct {
	Phone string `json:"phone"`
}
