// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package adminclient

import (
	"context"

	"admin-srv/pb/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminListItem           = admin.AdminListItem
	AdminLoginRequest       = admin.AdminLoginRequest
	AdminLoginResponse      = admin.AdminLoginResponse
	AdminLogoutRequest      = admin.AdminLogoutRequest
	AdminLogoutResponse     = admin.AdminLogoutResponse
	CarTypeListItem         = admin.CarTypeListItem
	ChangePasswordRequest   = admin.ChangePasswordRequest
	ChangePasswordResponse  = admin.ChangePasswordResponse
	CityListItem            = admin.CityListItem
	CreateAdminRequest      = admin.CreateAdminRequest
	CreateAdminResponse     = admin.CreateAdminResponse
	CreateCarTypeRequest    = admin.CreateCarTypeRequest
	CreateCarTypeResponse   = admin.CreateCarTypeResponse
	CreateCityRequest       = admin.CreateCityRequest
	CreateCityResponse      = admin.CreateCityResponse
	CreateMenuRequest       = admin.CreateMenuRequest
	CreateMenuResponse      = admin.CreateMenuResponse
	CreateRoleRequest       = admin.CreateRoleRequest
	CreateRoleResponse      = admin.CreateRoleResponse
	DeleteAdminRequest      = admin.DeleteAdminRequest
	DeleteAdminResponse     = admin.DeleteAdminResponse
	DeleteCarTypeRequest    = admin.DeleteCarTypeRequest
	DeleteCarTypeResponse   = admin.DeleteCarTypeResponse
	DeleteCityRequest       = admin.DeleteCityRequest
	DeleteCityResponse      = admin.DeleteCityResponse
	DeleteMenuRequest       = admin.DeleteMenuRequest
	DeleteMenuResponse      = admin.DeleteMenuResponse
	DeleteRoleRequest       = admin.DeleteRoleRequest
	DeleteRoleResponse      = admin.DeleteRoleResponse
	DispatchOrderRequest    = admin.DispatchOrderRequest
	DispatchOrderResponse   = admin.DispatchOrderResponse
	GetAdminDetailRequest   = admin.GetAdminDetailRequest
	GetAdminDetailResponse  = admin.GetAdminDetailResponse
	GetAdminListRequest     = admin.GetAdminListRequest
	GetAdminListResponse    = admin.GetAdminListResponse
	GetCarTypeListRequest   = admin.GetCarTypeListRequest
	GetCarTypeListResponse  = admin.GetCarTypeListResponse
	GetCityListRequest      = admin.GetCityListRequest
	GetCityListResponse     = admin.GetCityListResponse
	GetCurrentAdminRequest  = admin.GetCurrentAdminRequest
	GetCurrentAdminResponse = admin.GetCurrentAdminResponse
	GetMenuDetailRequest    = admin.GetMenuDetailRequest
	GetMenuDetailResponse   = admin.GetMenuDetailResponse
	GetMenuListRequest      = admin.GetMenuListRequest
	GetMenuListResponse     = admin.GetMenuListResponse
	GetOrderListRequest     = admin.GetOrderListRequest
	GetOrderListResponse    = admin.GetOrderListResponse
	GetRoleDetailRequest    = admin.GetRoleDetailRequest
	GetRoleDetailResponse   = admin.GetRoleDetailResponse
	GetRoleListRequest      = admin.GetRoleListRequest
	GetRoleListResponse     = admin.GetRoleListResponse
	MenuListItem            = admin.MenuListItem
	OrderListItem           = admin.OrderListItem
	RoleListItem            = admin.RoleListItem
	SyncOrderStatusRequest  = admin.SyncOrderStatusRequest
	SyncOrderStatusResponse = admin.SyncOrderStatusResponse
	UpdateAdminRequest      = admin.UpdateAdminRequest
	UpdateAdminResponse     = admin.UpdateAdminResponse
	UpdateCarTypeRequest    = admin.UpdateCarTypeRequest
	UpdateCarTypeResponse   = admin.UpdateCarTypeResponse
	UpdateCityRequest       = admin.UpdateCityRequest
	UpdateCityResponse      = admin.UpdateCityResponse
	UpdateMenuRequest       = admin.UpdateMenuRequest
	UpdateMenuResponse      = admin.UpdateMenuResponse
	UpdateRoleRequest       = admin.UpdateRoleRequest
	UpdateRoleResponse      = admin.UpdateRoleResponse

	Admin interface {
		// 管理员认证
		AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error)
		AdminLogout(ctx context.Context, in *AdminLogoutRequest, opts ...grpc.CallOption) (*AdminLogoutResponse, error)
		GetCurrentAdmin(ctx context.Context, in *GetCurrentAdminRequest, opts ...grpc.CallOption) (*GetCurrentAdminResponse, error)
		// 管理员管理
		GetAdminList(ctx context.Context, in *GetAdminListRequest, opts ...grpc.CallOption) (*GetAdminListResponse, error)
		GetAdminDetail(ctx context.Context, in *GetAdminDetailRequest, opts ...grpc.CallOption) (*GetAdminDetailResponse, error)
		CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error)
		UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...grpc.CallOption) (*UpdateAdminResponse, error)
		DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
		// 角色管理
		GetRoleList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error)
		GetRoleDetail(ctx context.Context, in *GetRoleDetailRequest, opts ...grpc.CallOption) (*GetRoleDetailResponse, error)
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error)
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error)
		// 菜单管理
		GetMenuList(ctx context.Context, in *GetMenuListRequest, opts ...grpc.CallOption) (*GetMenuListResponse, error)
		GetMenuDetail(ctx context.Context, in *GetMenuDetailRequest, opts ...grpc.CallOption) (*GetMenuDetailResponse, error)
		CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*UpdateMenuResponse, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*DeleteMenuResponse, error)
		// 城市配置
		GetCityList(ctx context.Context, in *GetCityListRequest, opts ...grpc.CallOption) (*GetCityListResponse, error)
		CreateCity(ctx context.Context, in *CreateCityRequest, opts ...grpc.CallOption) (*CreateCityResponse, error)
		UpdateCity(ctx context.Context, in *UpdateCityRequest, opts ...grpc.CallOption) (*UpdateCityResponse, error)
		DeleteCity(ctx context.Context, in *DeleteCityRequest, opts ...grpc.CallOption) (*DeleteCityResponse, error)
		// 车型配置
		GetCarTypeList(ctx context.Context, in *GetCarTypeListRequest, opts ...grpc.CallOption) (*GetCarTypeListResponse, error)
		CreateCarType(ctx context.Context, in *CreateCarTypeRequest, opts ...grpc.CallOption) (*CreateCarTypeResponse, error)
		UpdateCarType(ctx context.Context, in *UpdateCarTypeRequest, opts ...grpc.CallOption) (*UpdateCarTypeResponse, error)
		DeleteCarType(ctx context.Context, in *DeleteCarTypeRequest, opts ...grpc.CallOption) (*DeleteCarTypeResponse, error)
		// 订单管理（后台派单给司机）
		DispatchOrder(ctx context.Context, in *DispatchOrderRequest, opts ...grpc.CallOption) (*DispatchOrderResponse, error)
		GetOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetOrderListResponse, error)
		SyncOrderStatus(ctx context.Context, in *SyncOrderStatusRequest, opts ...grpc.CallOption) (*SyncOrderStatusResponse, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

// 管理员认证
func (m *defaultAdmin) AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AdminLogin(ctx, in, opts...)
}

func (m *defaultAdmin) AdminLogout(ctx context.Context, in *AdminLogoutRequest, opts ...grpc.CallOption) (*AdminLogoutResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AdminLogout(ctx, in, opts...)
}

func (m *defaultAdmin) GetCurrentAdmin(ctx context.Context, in *GetCurrentAdminRequest, opts ...grpc.CallOption) (*GetCurrentAdminResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetCurrentAdmin(ctx, in, opts...)
}

// 管理员管理
func (m *defaultAdmin) GetAdminList(ctx context.Context, in *GetAdminListRequest, opts ...grpc.CallOption) (*GetAdminListResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetAdminList(ctx, in, opts...)
}

func (m *defaultAdmin) GetAdminDetail(ctx context.Context, in *GetAdminDetailRequest, opts ...grpc.CallOption) (*GetAdminDetailResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetAdminDetail(ctx, in, opts...)
}

func (m *defaultAdmin) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CreateAdmin(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...grpc.CallOption) (*UpdateAdminResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateAdmin(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteAdmin(ctx, in, opts...)
}

func (m *defaultAdmin) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

// 角色管理
func (m *defaultAdmin) GetRoleList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

func (m *defaultAdmin) GetRoleDetail(ctx context.Context, in *GetRoleDetailRequest, opts ...grpc.CallOption) (*GetRoleDetailResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetRoleDetail(ctx, in, opts...)
}

func (m *defaultAdmin) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

// 菜单管理
func (m *defaultAdmin) GetMenuList(ctx context.Context, in *GetMenuListRequest, opts ...grpc.CallOption) (*GetMenuListResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetMenuList(ctx, in, opts...)
}

func (m *defaultAdmin) GetMenuDetail(ctx context.Context, in *GetMenuDetailRequest, opts ...grpc.CallOption) (*GetMenuDetailResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetMenuDetail(ctx, in, opts...)
}

func (m *defaultAdmin) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*CreateMenuResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*UpdateMenuResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*DeleteMenuResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

// 城市配置
func (m *defaultAdmin) GetCityList(ctx context.Context, in *GetCityListRequest, opts ...grpc.CallOption) (*GetCityListResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetCityList(ctx, in, opts...)
}

func (m *defaultAdmin) CreateCity(ctx context.Context, in *CreateCityRequest, opts ...grpc.CallOption) (*CreateCityResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CreateCity(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateCity(ctx context.Context, in *UpdateCityRequest, opts ...grpc.CallOption) (*UpdateCityResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateCity(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteCity(ctx context.Context, in *DeleteCityRequest, opts ...grpc.CallOption) (*DeleteCityResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteCity(ctx, in, opts...)
}

// 车型配置
func (m *defaultAdmin) GetCarTypeList(ctx context.Context, in *GetCarTypeListRequest, opts ...grpc.CallOption) (*GetCarTypeListResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetCarTypeList(ctx, in, opts...)
}

func (m *defaultAdmin) CreateCarType(ctx context.Context, in *CreateCarTypeRequest, opts ...grpc.CallOption) (*CreateCarTypeResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CreateCarType(ctx, in, opts...)
}

func (m *defaultAdmin) UpdateCarType(ctx context.Context, in *UpdateCarTypeRequest, opts ...grpc.CallOption) (*UpdateCarTypeResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.UpdateCarType(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteCarType(ctx context.Context, in *DeleteCarTypeRequest, opts ...grpc.CallOption) (*DeleteCarTypeResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteCarType(ctx, in, opts...)
}

// 订单管理（后台派单给司机）
func (m *defaultAdmin) DispatchOrder(ctx context.Context, in *DispatchOrderRequest, opts ...grpc.CallOption) (*DispatchOrderResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DispatchOrder(ctx, in, opts...)
}

func (m *defaultAdmin) GetOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetOrderListResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetOrderList(ctx, in, opts...)
}

func (m *defaultAdmin) SyncOrderStatus(ctx context.Context, in *SyncOrderStatusRequest, opts ...grpc.CallOption) (*SyncOrderStatusResponse, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.SyncOrderStatus(ctx, in, opts...)
}
