// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: driver.proto

package driver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driver_SendSms_FullMethodName                 = "/driver.Driver/SendSms"
	Driver_DriverLogin_FullMethodName             = "/driver.Driver/DriverLogin"
	Driver_DriverAuth_FullMethodName              = "/driver.Driver/DriverAuth"
	Driver_CartAuth_FullMethodName                = "/driver.Driver/CartAuth"
	Driver_OutLogin_FullMethodName                = "/driver.Driver/OutLogin"
	Driver_AcceptOrder_FullMethodName             = "/driver.Driver/AcceptOrder"
	Driver_CancelOrder_FullMethodName             = "/driver.Driver/CancelOrder"
	Driver_ArrivePassengerLocation_FullMethodName = "/driver.Driver/ArrivePassengerLocation"
	Driver_StartTrip_FullMethodName               = "/driver.Driver/StartTrip"
	Driver_DriverOrderDetail_FullMethodName       = "/driver.Driver/DriverOrderDetail"
	Driver_DriverOrderList_FullMethodName         = "/driver.Driver/DriverOrderList"
	Driver_DriverOrderHistory_FullMethodName      = "/driver.Driver/DriverOrderHistory"
	Driver_StartAcceptOrder_FullMethodName        = "/driver.Driver/StartAcceptOrder"
	Driver_StopAcceptOrder_FullMethodName         = "/driver.Driver/StopAcceptOrder"
	Driver_DriverOnline_FullMethodName            = "/driver.Driver/DriverOnline"
	Driver_DriverOffline_FullMethodName           = "/driver.Driver/DriverOffline"
	Driver_DriverRegister_FullMethodName          = "/driver.Driver/DriverRegister"
	Driver_GetDriverInfo_FullMethodName           = "/driver.Driver/GetDriverInfo"
	Driver_UpdateDriverInfo_FullMethodName        = "/driver.Driver/UpdateDriverInfo"
	Driver_SubmitDriverCert_FullMethodName        = "/driver.Driver/SubmitDriverCert"
	Driver_StatusDriverCert_FullMethodName        = "/driver.Driver/StatusDriverCert"
)

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverClient interface {
	// 司机认证模块
	SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsResp, error)
	DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error)
	DriverAuth(ctx context.Context, in *DriverAuthReq, opts ...grpc.CallOption) (*DriverAuthResp, error)
	CartAuth(ctx context.Context, in *CartAuthReq, opts ...grpc.CallOption) (*CartAuthResp, error)
	OutLogin(ctx context.Context, in *OutLoginReq, opts ...grpc.CallOption) (*OutLoginResp, error)
	// 司机接单与订单模块
	AcceptOrder(ctx context.Context, in *AcceptOrderReq, opts ...grpc.CallOption) (*AcceptOrderResp, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	ArrivePassengerLocation(ctx context.Context, in *ArrivePassengerLocationReq, opts ...grpc.CallOption) (*ArrivePassengerLocationResp, error)
	StartTrip(ctx context.Context, in *StartTripReq, opts ...grpc.CallOption) (*StartTripResp, error)
	DriverOrderDetail(ctx context.Context, in *DriverOrderDetailReq, opts ...grpc.CallOption) (*DriverOrderDetailResp, error)
	DriverOrderList(ctx context.Context, in *DriverOrderListReq, opts ...grpc.CallOption) (*DriverOrderListResp, error)
	DriverOrderHistory(ctx context.Context, in *DriverOrderHistoryReq, opts ...grpc.CallOption) (*DriverOrderHistoryResp, error)
	StartAcceptOrder(ctx context.Context, in *StartAcceptOrderReq, opts ...grpc.CallOption) (*StartAcceptOrderResp, error)
	StopAcceptOrder(ctx context.Context, in *StopAcceptOrderReq, opts ...grpc.CallOption) (*StopAcceptOrderResp, error)
	DriverOnline(ctx context.Context, in *DriverOnlineReq, opts ...grpc.CallOption) (*DriverOnlineResp, error)
	DriverOffline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error)
	// 司机信息模块
	DriverRegister(ctx context.Context, in *DriverRegisterReq, opts ...grpc.CallOption) (*DriverRegisterResp, error)
	GetDriverInfo(ctx context.Context, in *GetDriverInfoReq, opts ...grpc.CallOption) (*GetDriverInfoResp, error)
	UpdateDriverInfo(ctx context.Context, in *UpdateDriverInfoReq, opts ...grpc.CallOption) (*UpdateDriverInfoResp, error)
	SubmitDriverCert(ctx context.Context, in *SubmitDriverCertReq, opts ...grpc.CallOption) (*SubmitDriverCertResp, error)
	StatusDriverCert(ctx context.Context, in *StatusDriverCertReq, opts ...grpc.CallOption) (*StatusDriverCertResp, error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsResp)
	err := c.cc.Invoke(ctx, Driver_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverLoginResp)
	err := c.cc.Invoke(ctx, Driver_DriverLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverAuth(ctx context.Context, in *DriverAuthReq, opts ...grpc.CallOption) (*DriverAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverAuthResp)
	err := c.cc.Invoke(ctx, Driver_DriverAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) CartAuth(ctx context.Context, in *CartAuthReq, opts ...grpc.CallOption) (*CartAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartAuthResp)
	err := c.cc.Invoke(ctx, Driver_CartAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) OutLogin(ctx context.Context, in *OutLoginReq, opts ...grpc.CallOption) (*OutLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutLoginResp)
	err := c.cc.Invoke(ctx, Driver_OutLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) AcceptOrder(ctx context.Context, in *AcceptOrderReq, opts ...grpc.CallOption) (*AcceptOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOrderResp)
	err := c.cc.Invoke(ctx, Driver_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResp)
	err := c.cc.Invoke(ctx, Driver_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ArrivePassengerLocation(ctx context.Context, in *ArrivePassengerLocationReq, opts ...grpc.CallOption) (*ArrivePassengerLocationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArrivePassengerLocationResp)
	err := c.cc.Invoke(ctx, Driver_ArrivePassengerLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StartTrip(ctx context.Context, in *StartTripReq, opts ...grpc.CallOption) (*StartTripResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTripResp)
	err := c.cc.Invoke(ctx, Driver_StartTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverOrderDetail(ctx context.Context, in *DriverOrderDetailReq, opts ...grpc.CallOption) (*DriverOrderDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOrderDetailResp)
	err := c.cc.Invoke(ctx, Driver_DriverOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverOrderList(ctx context.Context, in *DriverOrderListReq, opts ...grpc.CallOption) (*DriverOrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOrderListResp)
	err := c.cc.Invoke(ctx, Driver_DriverOrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverOrderHistory(ctx context.Context, in *DriverOrderHistoryReq, opts ...grpc.CallOption) (*DriverOrderHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOrderHistoryResp)
	err := c.cc.Invoke(ctx, Driver_DriverOrderHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StartAcceptOrder(ctx context.Context, in *StartAcceptOrderReq, opts ...grpc.CallOption) (*StartAcceptOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAcceptOrderResp)
	err := c.cc.Invoke(ctx, Driver_StartAcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StopAcceptOrder(ctx context.Context, in *StopAcceptOrderReq, opts ...grpc.CallOption) (*StopAcceptOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAcceptOrderResp)
	err := c.cc.Invoke(ctx, Driver_StopAcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverOnline(ctx context.Context, in *DriverOnlineReq, opts ...grpc.CallOption) (*DriverOnlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOnlineResp)
	err := c.cc.Invoke(ctx, Driver_DriverOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverOffline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverOfflineResp)
	err := c.cc.Invoke(ctx, Driver_DriverOffline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DriverRegister(ctx context.Context, in *DriverRegisterReq, opts ...grpc.CallOption) (*DriverRegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverRegisterResp)
	err := c.cc.Invoke(ctx, Driver_DriverRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) GetDriverInfo(ctx context.Context, in *GetDriverInfoReq, opts ...grpc.CallOption) (*GetDriverInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverInfoResp)
	err := c.cc.Invoke(ctx, Driver_GetDriverInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) UpdateDriverInfo(ctx context.Context, in *UpdateDriverInfoReq, opts ...grpc.CallOption) (*UpdateDriverInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverInfoResp)
	err := c.cc.Invoke(ctx, Driver_UpdateDriverInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) SubmitDriverCert(ctx context.Context, in *SubmitDriverCertReq, opts ...grpc.CallOption) (*SubmitDriverCertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDriverCertResp)
	err := c.cc.Invoke(ctx, Driver_SubmitDriverCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StatusDriverCert(ctx context.Context, in *StatusDriverCertReq, opts ...grpc.CallOption) (*StatusDriverCertResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusDriverCertResp)
	err := c.cc.Invoke(ctx, Driver_StatusDriverCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
// All implementations must embed UnimplementedDriverServer
// for forward compatibility.
type DriverServer interface {
	// 司机认证模块
	SendSms(context.Context, *SendSmsReq) (*SendSmsResp, error)
	DriverLogin(context.Context, *DriverLoginReq) (*DriverLoginResp, error)
	DriverAuth(context.Context, *DriverAuthReq) (*DriverAuthResp, error)
	CartAuth(context.Context, *CartAuthReq) (*CartAuthResp, error)
	OutLogin(context.Context, *OutLoginReq) (*OutLoginResp, error)
	// 司机接单与订单模块
	AcceptOrder(context.Context, *AcceptOrderReq) (*AcceptOrderResp, error)
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error)
	ArrivePassengerLocation(context.Context, *ArrivePassengerLocationReq) (*ArrivePassengerLocationResp, error)
	StartTrip(context.Context, *StartTripReq) (*StartTripResp, error)
	DriverOrderDetail(context.Context, *DriverOrderDetailReq) (*DriverOrderDetailResp, error)
	DriverOrderList(context.Context, *DriverOrderListReq) (*DriverOrderListResp, error)
	DriverOrderHistory(context.Context, *DriverOrderHistoryReq) (*DriverOrderHistoryResp, error)
	StartAcceptOrder(context.Context, *StartAcceptOrderReq) (*StartAcceptOrderResp, error)
	StopAcceptOrder(context.Context, *StopAcceptOrderReq) (*StopAcceptOrderResp, error)
	DriverOnline(context.Context, *DriverOnlineReq) (*DriverOnlineResp, error)
	DriverOffline(context.Context, *DriverOfflineReq) (*DriverOfflineResp, error)
	// 司机信息模块
	DriverRegister(context.Context, *DriverRegisterReq) (*DriverRegisterResp, error)
	GetDriverInfo(context.Context, *GetDriverInfoReq) (*GetDriverInfoResp, error)
	UpdateDriverInfo(context.Context, *UpdateDriverInfoReq) (*UpdateDriverInfoResp, error)
	SubmitDriverCert(context.Context, *SubmitDriverCertReq) (*SubmitDriverCertResp, error)
	StatusDriverCert(context.Context, *StatusDriverCertReq) (*StatusDriverCertResp, error)
	mustEmbedUnimplementedDriverServer()
}

// UnimplementedDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServer struct{}

func (UnimplementedDriverServer) SendSms(context.Context, *SendSmsReq) (*SendSmsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedDriverServer) DriverLogin(context.Context, *DriverLoginReq) (*DriverLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverLogin not implemented")
}
func (UnimplementedDriverServer) DriverAuth(context.Context, *DriverAuthReq) (*DriverAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverAuth not implemented")
}
func (UnimplementedDriverServer) CartAuth(context.Context, *CartAuthReq) (*CartAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CartAuth not implemented")
}
func (UnimplementedDriverServer) OutLogin(context.Context, *OutLoginReq) (*OutLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OutLogin not implemented")
}
func (UnimplementedDriverServer) AcceptOrder(context.Context, *AcceptOrderReq) (*AcceptOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedDriverServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedDriverServer) ArrivePassengerLocation(context.Context, *ArrivePassengerLocationReq) (*ArrivePassengerLocationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ArrivePassengerLocation not implemented")
}
func (UnimplementedDriverServer) StartTrip(context.Context, *StartTripReq) (*StartTripResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTrip not implemented")
}
func (UnimplementedDriverServer) DriverOrderDetail(context.Context, *DriverOrderDetailReq) (*DriverOrderDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverOrderDetail not implemented")
}
func (UnimplementedDriverServer) DriverOrderList(context.Context, *DriverOrderListReq) (*DriverOrderListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverOrderList not implemented")
}
func (UnimplementedDriverServer) DriverOrderHistory(context.Context, *DriverOrderHistoryReq) (*DriverOrderHistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverOrderHistory not implemented")
}
func (UnimplementedDriverServer) StartAcceptOrder(context.Context, *StartAcceptOrderReq) (*StartAcceptOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAcceptOrder not implemented")
}
func (UnimplementedDriverServer) StopAcceptOrder(context.Context, *StopAcceptOrderReq) (*StopAcceptOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAcceptOrder not implemented")
}
func (UnimplementedDriverServer) DriverOnline(context.Context, *DriverOnlineReq) (*DriverOnlineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverOnline not implemented")
}
func (UnimplementedDriverServer) DriverOffline(context.Context, *DriverOfflineReq) (*DriverOfflineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverOffline not implemented")
}
func (UnimplementedDriverServer) DriverRegister(context.Context, *DriverRegisterReq) (*DriverRegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverRegister not implemented")
}
func (UnimplementedDriverServer) GetDriverInfo(context.Context, *GetDriverInfoReq) (*GetDriverInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverInfo not implemented")
}
func (UnimplementedDriverServer) UpdateDriverInfo(context.Context, *UpdateDriverInfoReq) (*UpdateDriverInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriverInfo not implemented")
}
func (UnimplementedDriverServer) SubmitDriverCert(context.Context, *SubmitDriverCertReq) (*SubmitDriverCertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDriverCert not implemented")
}
func (UnimplementedDriverServer) StatusDriverCert(context.Context, *StatusDriverCertReq) (*StatusDriverCertResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StatusDriverCert not implemented")
}
func (UnimplementedDriverServer) mustEmbedUnimplementedDriverServer() {}
func (UnimplementedDriverServer) testEmbeddedByValue()                {}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	// If the following call panics, it indicates UnimplementedDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).SendSms(ctx, req.(*SendSmsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverLogin(ctx, req.(*DriverLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverAuth(ctx, req.(*DriverAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_CartAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).CartAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_CartAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).CartAuth(ctx, req.(*CartAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_OutLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).OutLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_OutLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).OutLogin(ctx, req.(*OutLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).AcceptOrder(ctx, req.(*AcceptOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ArrivePassengerLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArrivePassengerLocationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).ArrivePassengerLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_ArrivePassengerLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).ArrivePassengerLocation(ctx, req.(*ArrivePassengerLocationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StartTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTripReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StartTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_StartTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StartTrip(ctx, req.(*StartTripReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOrderDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverOrderDetail(ctx, req.(*DriverOrderDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverOrderList(ctx, req.(*DriverOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOrderHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverOrderHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverOrderHistory(ctx, req.(*DriverOrderHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StartAcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAcceptOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StartAcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_StartAcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StartAcceptOrder(ctx, req.(*StartAcceptOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StopAcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAcceptOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StopAcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_StopAcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StopAcceptOrder(ctx, req.(*StopAcceptOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverOnline(ctx, req.(*DriverOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOfflineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverOffline(ctx, req.(*DriverOfflineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DriverRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DriverRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DriverRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DriverRegister(ctx, req.(*DriverRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_GetDriverInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).GetDriverInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_GetDriverInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).GetDriverInfo(ctx, req.(*GetDriverInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_UpdateDriverInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).UpdateDriverInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_UpdateDriverInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).UpdateDriverInfo(ctx, req.(*UpdateDriverInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_SubmitDriverCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDriverCertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).SubmitDriverCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_SubmitDriverCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).SubmitDriverCert(ctx, req.(*SubmitDriverCertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StatusDriverCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusDriverCertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StatusDriverCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_StatusDriverCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StatusDriverCert(ctx, req.(*StatusDriverCertReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSms",
			Handler:    _Driver_SendSms_Handler,
		},
		{
			MethodName: "DriverLogin",
			Handler:    _Driver_DriverLogin_Handler,
		},
		{
			MethodName: "DriverAuth",
			Handler:    _Driver_DriverAuth_Handler,
		},
		{
			MethodName: "CartAuth",
			Handler:    _Driver_CartAuth_Handler,
		},
		{
			MethodName: "OutLogin",
			Handler:    _Driver_OutLogin_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _Driver_AcceptOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Driver_CancelOrder_Handler,
		},
		{
			MethodName: "ArrivePassengerLocation",
			Handler:    _Driver_ArrivePassengerLocation_Handler,
		},
		{
			MethodName: "StartTrip",
			Handler:    _Driver_StartTrip_Handler,
		},
		{
			MethodName: "DriverOrderDetail",
			Handler:    _Driver_DriverOrderDetail_Handler,
		},
		{
			MethodName: "DriverOrderList",
			Handler:    _Driver_DriverOrderList_Handler,
		},
		{
			MethodName: "DriverOrderHistory",
			Handler:    _Driver_DriverOrderHistory_Handler,
		},
		{
			MethodName: "StartAcceptOrder",
			Handler:    _Driver_StartAcceptOrder_Handler,
		},
		{
			MethodName: "StopAcceptOrder",
			Handler:    _Driver_StopAcceptOrder_Handler,
		},
		{
			MethodName: "DriverOnline",
			Handler:    _Driver_DriverOnline_Handler,
		},
		{
			MethodName: "DriverOffline",
			Handler:    _Driver_DriverOffline_Handler,
		},
		{
			MethodName: "DriverRegister",
			Handler:    _Driver_DriverRegister_Handler,
		},
		{
			MethodName: "GetDriverInfo",
			Handler:    _Driver_GetDriverInfo_Handler,
		},
		{
			MethodName: "UpdateDriverInfo",
			Handler:    _Driver_UpdateDriverInfo_Handler,
		},
		{
			MethodName: "SubmitDriverCert",
			Handler:    _Driver_SubmitDriverCert_Handler,
		},
		{
			MethodName: "StatusDriverCert",
			Handler:    _Driver_StatusDriverCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}
