// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"admin-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: AdminLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/logout",
				Handler: AdminLogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/current",
				Handler: GetCurrentAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/list",
				Handler: GetAdminListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/detail",
				Handler: GetAdminDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/create",
				Handler: CreateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/update",
				Handler: UpdateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/delete",
				Handler: DeleteAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/change-password",
				Handler: ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/list",
				Handler: GetRoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/detail",
				Handler: GetRoleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/create",
				Handler: CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/update",
				Handler: UpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/delete",
				Handler: DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/list",
				Handler: GetMenuListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/detail",
				Handler: GetMenuDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/create",
				Handler: CreateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/update",
				Handler: UpdateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/delete",
				Handler: DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/city/list",
				Handler: GetCityListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/city/create",
				Handler: CreateCityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/city/update",
				Handler: UpdateCityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/city/delete",
				Handler: DeleteCityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cartype/list",
				Handler: GetCarTypeListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cartype/create",
				Handler: CreateCarTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cartype/update",
				Handler: UpdateCarTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cartype/delete",
				Handler: DeleteCarTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/dispatch",
				Handler: DispatchOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/list",
				Handler: GetOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/status/sync",
				Handler: SyncOrderStatusHandler(serverCtx),
			},
		},
	)
}
