// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"user-srv/pb/usermodel"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAddressReq               = usermodel.AddAddressReq
	AddAddressResp              = usermodel.AddAddressResp
	AddCouponReq                = usermodel.AddCouponReq
	AddCouponResp               = usermodel.AddCouponResp
	AddCouponTemplateReq        = usermodel.AddCouponTemplateReq
	AddCouponTemplateResp       = usermodel.AddCouponTemplateResp
	AddPassengerOrderReq        = usermodel.AddPassengerOrderReq
	AddPassengerOrderResp       = usermodel.AddPassengerOrderResp
	AddressInfo                 = usermodel.AddressInfo
	AvailableCouponTemplateInfo = usermodel.AvailableCouponTemplateInfo
	GetAvailableCouponsReq      = usermodel.GetAvailableCouponsReq
	GetAvailableCouponsResp     = usermodel.GetAvailableCouponsResp
	GetUnpaidOrdersReq          = usermodel.GetUnpaidOrdersReq
	GetUnpaidOrdersResp         = usermodel.GetUnpaidOrdersResp
	LoginReq                    = usermodel.LoginReq
	LoginResp                   = usermodel.LoginResp
	OrderFeeDetail              = usermodel.OrderFeeDetail
	PassengerOrderDetailReq     = usermodel.PassengerOrderDetailReq
	PassengerOrderDetailResp    = usermodel.PassengerOrderDetailResp
	PassengerOrderInfo          = usermodel.PassengerOrderInfo
	RealNameAuthReq             = usermodel.RealNameAuthReq
	RealNameAuthResp            = usermodel.RealNameAuthResp
	RegisterReq                 = usermodel.RegisterReq
	RegisterResp                = usermodel.RegisterResp
	SendCodeReq                 = usermodel.SendCodeReq
	SendCodeResp                = usermodel.SendCodeResp
	UpdatePhoneReq              = usermodel.UpdatePhoneReq
	UpdatePhoneResp             = usermodel.UpdatePhoneResp
	UserCouponInfo              = usermodel.UserCouponInfo
	UserCouponListReq           = usermodel.UserCouponListReq
	UserCouponListResp          = usermodel.UserCouponListResp
	UserDetailReq               = usermodel.UserDetailReq
	UserDetailResp              = usermodel.UserDetailResp
	UserInfo                    = usermodel.UserInfo
	UserListReq                 = usermodel.UserListReq
	UserListResp                = usermodel.UserListResp
	UserOrderListReq            = usermodel.UserOrderListReq
	UserOrderListResp           = usermodel.UserOrderListResp

	User interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
		GetUserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailResp, error)
		GetUserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
		UpdatePhone(ctx context.Context, in *UpdatePhoneReq, opts ...grpc.CallOption) (*UpdatePhoneResp, error)
		RealNameAuth(ctx context.Context, in *RealNameAuthReq, opts ...grpc.CallOption) (*RealNameAuthResp, error)
		AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*AddAddressResp, error)
		AddCoupon(ctx context.Context, in *AddCouponReq, opts ...grpc.CallOption) (*AddCouponResp, error)
		GetUserCouponList(ctx context.Context, in *UserCouponListReq, opts ...grpc.CallOption) (*UserCouponListResp, error)
		AddCouponTemplate(ctx context.Context, in *AddCouponTemplateReq, opts ...grpc.CallOption) (*AddCouponTemplateResp, error)
		GetAvailableCoupons(ctx context.Context, in *GetAvailableCouponsReq, opts ...grpc.CallOption) (*GetAvailableCouponsResp, error)
		AddPassengerOrder(ctx context.Context, in *AddPassengerOrderReq, opts ...grpc.CallOption) (*AddPassengerOrderResp, error)
		GetUserOrderList(ctx context.Context, in *UserOrderListReq, opts ...grpc.CallOption) (*UserOrderListResp, error)
		GetPassengerOrderDetail(ctx context.Context, in *PassengerOrderDetailReq, opts ...grpc.CallOption) (*PassengerOrderDetailResp, error)
		GetUnpaidOrders(ctx context.Context, in *GetUnpaidOrdersReq, opts ...grpc.CallOption) (*GetUnpaidOrdersResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

func (m *defaultUser) GetUserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}

func (m *defaultUser) GetUserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultUser) UpdatePhone(ctx context.Context, in *UpdatePhoneReq, opts ...grpc.CallOption) (*UpdatePhoneResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.UpdatePhone(ctx, in, opts...)
}

func (m *defaultUser) RealNameAuth(ctx context.Context, in *RealNameAuthReq, opts ...grpc.CallOption) (*RealNameAuthResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.RealNameAuth(ctx, in, opts...)
}

func (m *defaultUser) AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*AddAddressResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.AddAddress(ctx, in, opts...)
}

func (m *defaultUser) AddCoupon(ctx context.Context, in *AddCouponReq, opts ...grpc.CallOption) (*AddCouponResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.AddCoupon(ctx, in, opts...)
}

func (m *defaultUser) GetUserCouponList(ctx context.Context, in *UserCouponListReq, opts ...grpc.CallOption) (*UserCouponListResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetUserCouponList(ctx, in, opts...)
}

func (m *defaultUser) AddCouponTemplate(ctx context.Context, in *AddCouponTemplateReq, opts ...grpc.CallOption) (*AddCouponTemplateResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.AddCouponTemplate(ctx, in, opts...)
}

func (m *defaultUser) GetAvailableCoupons(ctx context.Context, in *GetAvailableCouponsReq, opts ...grpc.CallOption) (*GetAvailableCouponsResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetAvailableCoupons(ctx, in, opts...)
}

func (m *defaultUser) AddPassengerOrder(ctx context.Context, in *AddPassengerOrderReq, opts ...grpc.CallOption) (*AddPassengerOrderResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.AddPassengerOrder(ctx, in, opts...)
}

func (m *defaultUser) GetUserOrderList(ctx context.Context, in *UserOrderListReq, opts ...grpc.CallOption) (*UserOrderListResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetUserOrderList(ctx, in, opts...)
}

func (m *defaultUser) GetPassengerOrderDetail(ctx context.Context, in *PassengerOrderDetailReq, opts ...grpc.CallOption) (*PassengerOrderDetailResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetPassengerOrderDetail(ctx, in, opts...)
}

func (m *defaultUser) GetUnpaidOrders(ctx context.Context, in *GetUnpaidOrdersReq, opts ...grpc.CallOption) (*GetUnpaidOrdersResp, error) {
	client := usermodel.NewUserClient(m.cli.Conn())
	return client.GetUnpaidOrders(ctx, in, opts...)
}
