// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/service/list",
				Handler: GetServiceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/addAddress",
				Handler: AddAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/addCoupon",
				Handler: AddCouponHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/addPassengerOrderReq",
				Handler: AddPassengerOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: GetUserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/getPassengerOrderDetail",
				Handler: GetPassengerOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/getUnpaidOrders",
				Handler: GetUnpaidOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/getUserCoupon",
				Handler: GetUserCouponHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/getUserOrderList",
				Handler: GetUserOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/realNameAuth",
				Handler: RealNameAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sendCode",
				Handler: SendCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/updatePhone",
				Handler: UpdatePhoneHandler(serverCtx),
			},
		},
	)
}
