// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package server

import (
	"context"

	"admin-srv/internal/logic"
	"admin-srv/internal/svc"
	"admin-srv/pb/admin"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// 管理员认证（增强版：防暴力破解、登录日志、设备检测）
func (s *AdminServer) AdminLogin(ctx context.Context, in *admin.AdminLoginRequest) (*admin.AdminLoginResponse, error) {
	l := logic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}

func (s *AdminServer) AdminLogout(ctx context.Context, in *admin.AdminLogoutRequest) (*admin.AdminLogoutResponse, error) {
	l := logic.NewAdminLogoutLogic(ctx, s.svcCtx)
	return l.AdminLogout(in)
}

func (s *AdminServer) GetCurrentAdmin(ctx context.Context, in *admin.GetCurrentAdminRequest) (*admin.GetCurrentAdminResponse, error) {
	l := logic.NewGetCurrentAdminLogic(ctx, s.svcCtx)
	return l.GetCurrentAdmin(in)
}

// 管理员管理
func (s *AdminServer) GetAdminList(ctx context.Context, in *admin.GetAdminListRequest) (*admin.GetAdminListResponse, error) {
	l := logic.NewGetAdminListLogic(ctx, s.svcCtx)
	return l.GetAdminList(in)
}

func (s *AdminServer) GetAdminDetail(ctx context.Context, in *admin.GetAdminDetailRequest) (*admin.GetAdminDetailResponse, error) {
	l := logic.NewGetAdminDetailLogic(ctx, s.svcCtx)
	return l.GetAdminDetail(in)
}

func (s *AdminServer) CreateAdmin(ctx context.Context, in *admin.CreateAdminRequest) (*admin.CreateAdminResponse, error) {
	l := logic.NewCreateAdminLogic(ctx, s.svcCtx)
	return l.CreateAdmin(in)
}

func (s *AdminServer) UpdateAdmin(ctx context.Context, in *admin.UpdateAdminRequest) (*admin.UpdateAdminResponse, error) {
	l := logic.NewUpdateAdminLogic(ctx, s.svcCtx)
	return l.UpdateAdmin(in)
}

func (s *AdminServer) DeleteAdmin(ctx context.Context, in *admin.DeleteAdminRequest) (*admin.DeleteAdminResponse, error) {
	l := logic.NewDeleteAdminLogic(ctx, s.svcCtx)
	return l.DeleteAdmin(in)
}

func (s *AdminServer) ChangePassword(ctx context.Context, in *admin.ChangePasswordRequest) (*admin.ChangePasswordResponse, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

// 角色管理
func (s *AdminServer) GetRoleList(ctx context.Context, in *admin.GetRoleListRequest) (*admin.GetRoleListResponse, error) {
	l := logic.NewGetRoleListLogic(ctx, s.svcCtx)
	return l.GetRoleList(in)
}

func (s *AdminServer) GetRoleDetail(ctx context.Context, in *admin.GetRoleDetailRequest) (*admin.GetRoleDetailResponse, error) {
	l := logic.NewGetRoleDetailLogic(ctx, s.svcCtx)
	return l.GetRoleDetail(in)
}

func (s *AdminServer) CreateRole(ctx context.Context, in *admin.CreateRoleRequest) (*admin.CreateRoleResponse, error) {
	l := logic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *AdminServer) UpdateRole(ctx context.Context, in *admin.UpdateRoleRequest) (*admin.UpdateRoleResponse, error) {
	l := logic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *AdminServer) DeleteRole(ctx context.Context, in *admin.DeleteRoleRequest) (*admin.DeleteRoleResponse, error) {
	l := logic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

// 菜单管理
func (s *AdminServer) GetMenuList(ctx context.Context, in *admin.GetMenuListRequest) (*admin.GetMenuListResponse, error) {
	l := logic.NewGetMenuListLogic(ctx, s.svcCtx)
	return l.GetMenuList(in)
}

func (s *AdminServer) GetMenuDetail(ctx context.Context, in *admin.GetMenuDetailRequest) (*admin.GetMenuDetailResponse, error) {
	l := logic.NewGetMenuDetailLogic(ctx, s.svcCtx)
	return l.GetMenuDetail(in)
}

func (s *AdminServer) CreateMenu(ctx context.Context, in *admin.CreateMenuRequest) (*admin.CreateMenuResponse, error) {
	l := logic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *AdminServer) UpdateMenu(ctx context.Context, in *admin.UpdateMenuRequest) (*admin.UpdateMenuResponse, error) {
	l := logic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *AdminServer) DeleteMenu(ctx context.Context, in *admin.DeleteMenuRequest) (*admin.DeleteMenuResponse, error) {
	l := logic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

// 城市配置
func (s *AdminServer) GetCityList(ctx context.Context, in *admin.GetCityListRequest) (*admin.GetCityListResponse, error) {
	l := logic.NewGetCityListLogic(ctx, s.svcCtx)
	return l.GetCityList(in)
}

func (s *AdminServer) CreateCity(ctx context.Context, in *admin.CreateCityRequest) (*admin.CreateCityResponse, error) {
	l := logic.NewCreateCityLogic(ctx, s.svcCtx)
	return l.CreateCity(in)
}

func (s *AdminServer) UpdateCity(ctx context.Context, in *admin.UpdateCityRequest) (*admin.UpdateCityResponse, error) {
	l := logic.NewUpdateCityLogic(ctx, s.svcCtx)
	return l.UpdateCity(in)
}

func (s *AdminServer) DeleteCity(ctx context.Context, in *admin.DeleteCityRequest) (*admin.DeleteCityResponse, error) {
	l := logic.NewDeleteCityLogic(ctx, s.svcCtx)
	return l.DeleteCity(in)
}

// 车型配置
func (s *AdminServer) GetCarTypeList(ctx context.Context, in *admin.GetCarTypeListRequest) (*admin.GetCarTypeListResponse, error) {
	l := logic.NewGetCarTypeListLogic(ctx, s.svcCtx)
	return l.GetCarTypeList(in)
}

func (s *AdminServer) CreateCarType(ctx context.Context, in *admin.CreateCarTypeRequest) (*admin.CreateCarTypeResponse, error) {
	l := logic.NewCreateCarTypeLogic(ctx, s.svcCtx)
	return l.CreateCarType(in)
}

func (s *AdminServer) UpdateCarType(ctx context.Context, in *admin.UpdateCarTypeRequest) (*admin.UpdateCarTypeResponse, error) {
	l := logic.NewUpdateCarTypeLogic(ctx, s.svcCtx)
	return l.UpdateCarType(in)
}

func (s *AdminServer) DeleteCarType(ctx context.Context, in *admin.DeleteCarTypeRequest) (*admin.DeleteCarTypeResponse, error) {
	l := logic.NewDeleteCarTypeLogic(ctx, s.svcCtx)
	return l.DeleteCarType(in)
}

// 订单管理（后台派单给司机）
func (s *AdminServer) DispatchOrder(ctx context.Context, in *admin.DispatchOrderRequest) (*admin.DispatchOrderResponse, error) {
	l := logic.NewDispatchOrderLogic(ctx, s.svcCtx)
	return l.DispatchOrder(in)
}

func (s *AdminServer) GetOrderList(ctx context.Context, in *admin.GetOrderListRequest) (*admin.GetOrderListResponse, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

func (s *AdminServer) SyncOrderStatus(ctx context.Context, in *admin.SyncOrderStatusRequest) (*admin.SyncOrderStatusResponse, error) {
	l := logic.NewSyncOrderStatusLogic(ctx, s.svcCtx)
	return l.SyncOrderStatus(in)
}


