// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"driver-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cartAuth",
				Handler: CartAuthReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/driverAuth",
				Handler: DriverAuthReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/driverLogin",
				Handler: DriverLoginReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/outLogin",
				Handler: OutLoginReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendSms",
				Handler: SendSmsReqHandler(serverCtx),
			},
		},
	)
}
