// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"user-srv/internal/logic"
	"user-srv/internal/svc"
	"user-srv/pb/usermodel"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	usermodel.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *usermodel.RegisterReq) (*usermodel.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *usermodel.LoginReq) (*usermodel.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) SendCode(ctx context.Context, in *usermodel.SendCodeReq) (*usermodel.SendCodeResp, error) {
	l := logic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

func (s *UserServer) GetUserDetail(ctx context.Context, in *usermodel.UserDetailReq) (*usermodel.UserDetailResp, error) {
	l := logic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}

func (s *UserServer) GetUserList(ctx context.Context, in *usermodel.UserListReq) (*usermodel.UserListResp, error) {
	l := logic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *UserServer) UpdatePhone(ctx context.Context, in *usermodel.UpdatePhoneReq) (*usermodel.UpdatePhoneResp, error) {
	l := logic.NewUpdatePhoneLogic(ctx, s.svcCtx)
	return l.UpdatePhone(in)
}

func (s *UserServer) RealNameAuth(ctx context.Context, in *usermodel.RealNameAuthReq) (*usermodel.RealNameAuthResp, error) {
	l := logic.NewRealNameAuthLogic(ctx, s.svcCtx)
	return l.RealNameAuth(in)
}

func (s *UserServer) AddAddress(ctx context.Context, in *usermodel.AddAddressReq) (*usermodel.AddAddressResp, error) {
	l := logic.NewAddAddressLogic(ctx, s.svcCtx)
	return l.AddAddress(in)
}

func (s *UserServer) AddCoupon(ctx context.Context, in *usermodel.AddCouponReq) (*usermodel.AddCouponResp, error) {
	l := logic.NewAddCouponLogic(ctx, s.svcCtx)
	return l.AddCoupon(in)
}

func (s *UserServer) GetUserCouponList(ctx context.Context, in *usermodel.UserCouponListReq) (*usermodel.UserCouponListResp, error) {
	l := logic.NewGetUserCouponListLogic(ctx, s.svcCtx)
	return l.GetUserCouponList(in)
}

func (s *UserServer) AddCouponTemplate(ctx context.Context, in *usermodel.AddCouponTemplateReq) (*usermodel.AddCouponTemplateResp, error) {
	l := logic.NewAddCouponTemplateLogic(ctx, s.svcCtx)
	return l.AddCouponTemplate(in)
}

func (s *UserServer) GetAvailableCoupons(ctx context.Context, in *usermodel.GetAvailableCouponsReq) (*usermodel.GetAvailableCouponsResp, error) {
	l := logic.NewGetAvailableCouponsLogic(ctx, s.svcCtx)
	return l.GetAvailableCoupons(in)
}

func (s *UserServer) AddPassengerOrder(ctx context.Context, in *usermodel.AddPassengerOrderReq) (*usermodel.AddPassengerOrderResp, error) {
	l := logic.NewAddPassengerOrderLogic(ctx, s.svcCtx)
	return l.AddPassengerOrder(in)
}

func (s *UserServer) GetUserOrderList(ctx context.Context, in *usermodel.UserOrderListReq) (*usermodel.UserOrderListResp, error) {
	l := logic.NewGetUserOrderListLogic(ctx, s.svcCtx)
	return l.GetUserOrderList(in)
}

func (s *UserServer) GetPassengerOrderDetail(ctx context.Context, in *usermodel.PassengerOrderDetailReq) (*usermodel.PassengerOrderDetailResp, error) {
	l := logic.NewGetPassengerOrderDetailLogic(ctx, s.svcCtx)
	return l.GetPassengerOrderDetail(in)
}

func (s *UserServer) GetUnpaidOrders(ctx context.Context, in *usermodel.GetUnpaidOrdersReq) (*usermodel.GetUnpaidOrdersResp, error) {
	l := logic.NewGetUnpaidOrdersLogic(ctx, s.svcCtx)
	return l.GetUnpaidOrders(in)
}
