// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: user.proto

package usermodel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_Register_FullMethodName                = "/user.User/Register"
	User_Login_FullMethodName                   = "/user.User/Login"
	User_SendCode_FullMethodName                = "/user.User/SendCode"
	User_GetUserDetail_FullMethodName           = "/user.User/GetUserDetail"
	User_GetUserList_FullMethodName             = "/user.User/GetUserList"
	User_UpdatePhone_FullMethodName             = "/user.User/UpdatePhone"
	User_RealNameAuth_FullMethodName            = "/user.User/RealNameAuth"
	User_AddAddress_FullMethodName              = "/user.User/AddAddress"
	User_AddCoupon_FullMethodName               = "/user.User/AddCoupon"
	User_GetUserCouponList_FullMethodName       = "/user.User/GetUserCouponList"
	User_AddCouponTemplate_FullMethodName       = "/user.User/AddCouponTemplate"
	User_GetAvailableCoupons_FullMethodName     = "/user.User/GetAvailableCoupons"
	User_AddPassengerOrder_FullMethodName       = "/user.User/AddPassengerOrder"
	User_GetUserOrderList_FullMethodName        = "/user.User/GetUserOrderList"
	User_GetPassengerOrderDetail_FullMethodName = "/user.User/GetPassengerOrderDetail"
	User_GetUnpaidOrders_FullMethodName         = "/user.User/GetUnpaidOrders"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
	GetUserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailResp, error)
	GetUserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
	UpdatePhone(ctx context.Context, in *UpdatePhoneReq, opts ...grpc.CallOption) (*UpdatePhoneResp, error)
	RealNameAuth(ctx context.Context, in *RealNameAuthReq, opts ...grpc.CallOption) (*RealNameAuthResp, error)
	AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*AddAddressResp, error)
	AddCoupon(ctx context.Context, in *AddCouponReq, opts ...grpc.CallOption) (*AddCouponResp, error)
	GetUserCouponList(ctx context.Context, in *UserCouponListReq, opts ...grpc.CallOption) (*UserCouponListResp, error)
	AddCouponTemplate(ctx context.Context, in *AddCouponTemplateReq, opts ...grpc.CallOption) (*AddCouponTemplateResp, error)
	GetAvailableCoupons(ctx context.Context, in *GetAvailableCouponsReq, opts ...grpc.CallOption) (*GetAvailableCouponsResp, error)
	AddPassengerOrder(ctx context.Context, in *AddPassengerOrderReq, opts ...grpc.CallOption) (*AddPassengerOrderResp, error)
	GetUserOrderList(ctx context.Context, in *UserOrderListReq, opts ...grpc.CallOption) (*UserOrderListResp, error)
	GetPassengerOrderDetail(ctx context.Context, in *PassengerOrderDetailReq, opts ...grpc.CallOption) (*PassengerOrderDetailResp, error)
	GetUnpaidOrders(ctx context.Context, in *GetUnpaidOrdersReq, opts ...grpc.CallOption) (*GetUnpaidOrdersResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, User_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCodeResp)
	err := c.cc.Invoke(ctx, User_SendCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDetailResp)
	err := c.cc.Invoke(ctx, User_GetUserDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, User_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdatePhone(ctx context.Context, in *UpdatePhoneReq, opts ...grpc.CallOption) (*UpdatePhoneResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePhoneResp)
	err := c.cc.Invoke(ctx, User_UpdatePhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RealNameAuth(ctx context.Context, in *RealNameAuthReq, opts ...grpc.CallOption) (*RealNameAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealNameAuthResp)
	err := c.cc.Invoke(ctx, User_RealNameAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*AddAddressResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAddressResp)
	err := c.cc.Invoke(ctx, User_AddAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddCoupon(ctx context.Context, in *AddCouponReq, opts ...grpc.CallOption) (*AddCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCouponResp)
	err := c.cc.Invoke(ctx, User_AddCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserCouponList(ctx context.Context, in *UserCouponListReq, opts ...grpc.CallOption) (*UserCouponListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCouponListResp)
	err := c.cc.Invoke(ctx, User_GetUserCouponList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddCouponTemplate(ctx context.Context, in *AddCouponTemplateReq, opts ...grpc.CallOption) (*AddCouponTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCouponTemplateResp)
	err := c.cc.Invoke(ctx, User_AddCouponTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAvailableCoupons(ctx context.Context, in *GetAvailableCouponsReq, opts ...grpc.CallOption) (*GetAvailableCouponsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableCouponsResp)
	err := c.cc.Invoke(ctx, User_GetAvailableCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddPassengerOrder(ctx context.Context, in *AddPassengerOrderReq, opts ...grpc.CallOption) (*AddPassengerOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPassengerOrderResp)
	err := c.cc.Invoke(ctx, User_AddPassengerOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserOrderList(ctx context.Context, in *UserOrderListReq, opts ...grpc.CallOption) (*UserOrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOrderListResp)
	err := c.cc.Invoke(ctx, User_GetUserOrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetPassengerOrderDetail(ctx context.Context, in *PassengerOrderDetailReq, opts ...grpc.CallOption) (*PassengerOrderDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PassengerOrderDetailResp)
	err := c.cc.Invoke(ctx, User_GetPassengerOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUnpaidOrders(ctx context.Context, in *GetUnpaidOrdersReq, opts ...grpc.CallOption) (*GetUnpaidOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnpaidOrdersResp)
	err := c.cc.Invoke(ctx, User_GetUnpaidOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	SendCode(context.Context, *SendCodeReq) (*SendCodeResp, error)
	GetUserDetail(context.Context, *UserDetailReq) (*UserDetailResp, error)
	GetUserList(context.Context, *UserListReq) (*UserListResp, error)
	UpdatePhone(context.Context, *UpdatePhoneReq) (*UpdatePhoneResp, error)
	RealNameAuth(context.Context, *RealNameAuthReq) (*RealNameAuthResp, error)
	AddAddress(context.Context, *AddAddressReq) (*AddAddressResp, error)
	AddCoupon(context.Context, *AddCouponReq) (*AddCouponResp, error)
	GetUserCouponList(context.Context, *UserCouponListReq) (*UserCouponListResp, error)
	AddCouponTemplate(context.Context, *AddCouponTemplateReq) (*AddCouponTemplateResp, error)
	GetAvailableCoupons(context.Context, *GetAvailableCouponsReq) (*GetAvailableCouponsResp, error)
	AddPassengerOrder(context.Context, *AddPassengerOrderReq) (*AddPassengerOrderResp, error)
	GetUserOrderList(context.Context, *UserOrderListReq) (*UserOrderListResp, error)
	GetPassengerOrderDetail(context.Context, *PassengerOrderDetailReq) (*PassengerOrderDetailResp, error)
	GetUnpaidOrders(context.Context, *GetUnpaidOrdersReq) (*GetUnpaidOrdersResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServer) SendCode(context.Context, *SendCodeReq) (*SendCodeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCode not implemented")
}
func (UnimplementedUserServer) GetUserDetail(context.Context, *UserDetailReq) (*UserDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (UnimplementedUserServer) GetUserList(context.Context, *UserListReq) (*UserListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedUserServer) UpdatePhone(context.Context, *UpdatePhoneReq) (*UpdatePhoneResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePhone not implemented")
}
func (UnimplementedUserServer) RealNameAuth(context.Context, *RealNameAuthReq) (*RealNameAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RealNameAuth not implemented")
}
func (UnimplementedUserServer) AddAddress(context.Context, *AddAddressReq) (*AddAddressResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAddress not implemented")
}
func (UnimplementedUserServer) AddCoupon(context.Context, *AddCouponReq) (*AddCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCoupon not implemented")
}
func (UnimplementedUserServer) GetUserCouponList(context.Context, *UserCouponListReq) (*UserCouponListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCouponList not implemented")
}
func (UnimplementedUserServer) AddCouponTemplate(context.Context, *AddCouponTemplateReq) (*AddCouponTemplateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCouponTemplate not implemented")
}
func (UnimplementedUserServer) GetAvailableCoupons(context.Context, *GetAvailableCouponsReq) (*GetAvailableCouponsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableCoupons not implemented")
}
func (UnimplementedUserServer) AddPassengerOrder(context.Context, *AddPassengerOrderReq) (*AddPassengerOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPassengerOrder not implemented")
}
func (UnimplementedUserServer) GetUserOrderList(context.Context, *UserOrderListReq) (*UserOrderListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserOrderList not implemented")
}
func (UnimplementedUserServer) GetPassengerOrderDetail(context.Context, *PassengerOrderDetailReq) (*PassengerOrderDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPassengerOrderDetail not implemented")
}
func (UnimplementedUserServer) GetUnpaidOrders(context.Context, *GetUnpaidOrdersReq) (*GetUnpaidOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnpaidOrders not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SendCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SendCode(ctx, req.(*SendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserDetail(ctx, req.(*UserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserList(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdatePhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdatePhone(ctx, req.(*UpdatePhoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RealNameAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealNameAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RealNameAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_RealNameAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RealNameAuth(ctx, req.(*RealNameAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddAddress(ctx, req.(*AddAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddCoupon(ctx, req.(*AddCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserCouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCouponListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserCouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserCouponList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserCouponList(ctx, req.(*UserCouponListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddCouponTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCouponTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddCouponTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddCouponTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddCouponTemplate(ctx, req.(*AddCouponTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAvailableCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableCouponsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAvailableCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetAvailableCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAvailableCoupons(ctx, req.(*GetAvailableCouponsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddPassengerOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPassengerOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddPassengerOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddPassengerOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddPassengerOrder(ctx, req.(*AddPassengerOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserOrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserOrderList(ctx, req.(*UserOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetPassengerOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerOrderDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetPassengerOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetPassengerOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetPassengerOrderDetail(ctx, req.(*PassengerOrderDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUnpaidOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnpaidOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUnpaidOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUnpaidOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUnpaidOrders(ctx, req.(*GetUnpaidOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "SendCode",
			Handler:    _User_SendCode_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _User_GetUserDetail_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _User_GetUserList_Handler,
		},
		{
			MethodName: "UpdatePhone",
			Handler:    _User_UpdatePhone_Handler,
		},
		{
			MethodName: "RealNameAuth",
			Handler:    _User_RealNameAuth_Handler,
		},
		{
			MethodName: "AddAddress",
			Handler:    _User_AddAddress_Handler,
		},
		{
			MethodName: "AddCoupon",
			Handler:    _User_AddCoupon_Handler,
		},
		{
			MethodName: "GetUserCouponList",
			Handler:    _User_GetUserCouponList_Handler,
		},
		{
			MethodName: "AddCouponTemplate",
			Handler:    _User_AddCouponTemplate_Handler,
		},
		{
			MethodName: "GetAvailableCoupons",
			Handler:    _User_GetAvailableCoupons_Handler,
		},
		{
			MethodName: "AddPassengerOrder",
			Handler:    _User_AddPassengerOrder_Handler,
		},
		{
			MethodName: "GetUserOrderList",
			Handler:    _User_GetUserOrderList_Handler,
		},
		{
			MethodName: "GetPassengerOrderDetail",
			Handler:    _User_GetPassengerOrderDetail_Handler,
		},
		{
			MethodName: "GetUnpaidOrders",
			Handler:    _User_GetUnpaidOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
