// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

// ========== 统一响应 ==========

type Request struct {
	Code    int32       `json:"code"`    // 状态码
	Message string      `json:"message"` // 消息
	Data    interface{} `json:"data"`
}

// ========== 管理员认证 ==========

type AdminLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminLogoutRequest struct {
	AdminId int32 `json:"admin_id"`
}

type GetCurrentAdminRequest struct {
	AdminId int32 `json:"admin_id"`
}

// ========== 管理员管理 ==========

type GetAdminListRequest struct {
	Page     int32  `json:"page,optional"`
	PageSize int32  `json:"page_size,optional"`
	Keyword  string `json:"keyword,optional"`
}

type AdminListItem struct {
	Id            int32  `json:"id"`
	Username      string `json:"username"`
	RoleId        int32  `json:"role_id"`
	RoleName      string `json:"role_name"`
	Status        int32  `json:"status"`
	LastLoginTime string `json:"last_login_time"`
}

type GetAdminDetailRequest struct {
	AdminId int32 `json:"admin_id"`
}

type CreateAdminRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	RoleId   int32  `json:"role_id"`
}

type UpdateAdminRequest struct {
	AdminId  int32  `json:"admin_id"`
	Username string `json:"username"`
	RoleId   int32  `json:"role_id"`
	Status   int32  `json:"status"`
}

type DeleteAdminRequest struct {
	AdminId int32 `json:"admin_id"`
}

type ChangePasswordRequest struct {
	AdminId     int32  `json:"admin_id"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

// ========== 角色管理 ==========

type GetRoleListRequest struct {
	Page     int32  `json:"page,optional"`
	PageSize int32  `json:"page_size,optional"`
	Keyword  string `json:"keyword,optional"`
}

type RoleListItem struct {
	Id      int32  `json:"id"`
	Name    string `json:"name"`
	Remark  string `json:"remark"`
	MenuIds int32  `json:"menu_ids"`
}

type GetRoleDetailRequest struct {
	RoleId int32 `json:"role_id"`
}

type CreateRoleRequest struct {
	Name    string  `json:"name"`
	Remark  string  `json:"remark,optional"`
	MenuIds []int32 `json:"menu_ids"`
}

type UpdateRoleRequest struct {
	RoleId  int32  `json:"role_id"`
	Name    string  `json:"name"`
	Remark  string  `json:"remark,optional"`
	MenuIds []int32 `json:"menu_ids"`
}

type DeleteRoleRequest struct {
	RoleId int32 `json:"role_id"`
}

// ========== 菜单管理 ==========

type GetMenuListRequest struct{}

type MenuListItem struct {
	Id       int32          `json:"id"`
	ParentId int32          `json:"parent_id"`
	Name     string         `json:"name"`
	Path     string         `json:"path"`
	Icon     string         `json:"icon,optional"`
	Sort     int32          `json:"sort"`
	Children []MenuListItem `json:"children,omitempty"`
}

type GetMenuDetailRequest struct {
	MenuId int32 `json:"menu_id"`
}

type CreateMenuRequest struct {
	ParentId int32  `json:"parent_id"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	Icon     string `json:"icon,optional"`
	Sort     int32  `json:"sort"`
}

type UpdateMenuRequest struct {
	MenuId   int32  `json:"menu_id"`
	ParentId int32  `json:"parent_id"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	Icon     string `json:"icon,optional"`
	Sort     int32  `json:"sort"`
}

type DeleteMenuRequest struct {
	MenuId int32 `json:"menu_id"`
}

// ========== 城市配置 ==========

type GetCityListRequest struct {
	Page     int32  `json:"page,optional"`
	PageSize int32  `json:"page_size,optional"`
	Keyword  string `json:"keyword,optional"`
}

type CityListItem struct {
	Id       int32  `json:"id"`
	CityCode string `json:"city_code"`
	CityName string `json:"city_name"`
	Status   int32  `json:"status"`
}

type CreateCityRequest struct {
	CityCode string `json:"city_code"`
	CityName string `json:"city_name"`
	Status   int32  `json:"status"`
}

type UpdateCityRequest struct {
	Id       int32  `json:"id"`
	CityCode string `json:"city_code"`
	CityName string `json:"city_name"`
	Status   int32  `json:"status"`
}

type DeleteCityRequest struct {
	Id int32 `json:"id"`
}

// ========== 车型配置 ==========

type GetCarTypeListRequest struct {
	Page     int32  `json:"page,optional"`
	PageSize int32  `json:"page_size,optional"`
}

type CarTypeListItem struct {
	Id          int32   `json:"id"`
	TypeName    string  `json:"type_name"`
	BasePrice   float64 `json:"base_price"`
	KmPrice     float64 `json:"km_price"`
	MinutePrice float64 `json:"minute_price"`
	Status      int32   `json:"status"`
}

type CreateCarTypeRequest struct {
	TypeName    string  `json:"type_name"`
	BasePrice   float64 `json:"base_price"`
	KmPrice     float64 `json:"km_price"`
	MinutePrice float64 `json:"minute_price"`
	Status      int32   `json:"status"`
}

type UpdateCarTypeRequest struct {
	Id          int32   `json:"id"`
	TypeName    string  `json:"type_name"`
	BasePrice   float64 `json:"base_price"`
	KmPrice     float64 `json:"km_price"`
	MinutePrice float64 `json:"minute_price"`
	Status      int32   `json:"status"`
}

type DeleteCarTypeRequest struct {
	Id int32 `json:"id"`
}

// ========== 订单管理（后台派单）==========

type DispatchOrderRequest struct {
	PassengerName  string  `json:"passenger_name"`             // 乘客姓名
	PassengerPhone string  `json:"passenger_phone"`            // 乘客电话
	StartAddress   string  `json:"start_address"`              // 出发地址
	StartLng       float64 `json:"start_lng"`                  // 出发地经度
	StartLat       float64 `json:"start_lat"`                  // 出发地纬度
	EndAddress     string  `json:"end_address"`                // 目的地地址
	EndLng         float64 `json:"end_lng"`                    // 目的地经度
	EndLat         float64 `json:"end_lat"`                    // 目的地纬度
	CarType        int32   `json:"car_type"`                   // 车型：1-经济型，2-舒适型，3-商务型，4-豪华型
	DriverId       int64   `json:"driver_id"`                  // 目标司机ID
	Remark         string  `json:"remark,optional"`            // 备注
	EstimatedPrice float64 `json:"estimated_price,optional"`   // 预估价格
}

type GetOrderListRequest struct {
	Page     int32  `json:"page,optional"`
	PageSize int32  `json:"page_size,optional"`
	Keyword  string `json:"keyword,optional"`  // 关键词搜索
	Status   int32  `json:"status,optional"`    // 状态筛选
}

type SyncOrderStatusRequest struct {
	OrderId      string  `json:"order_id"`
	Status       int32   `json:"status"`
	DriverId     int64   `json:"driver_id,optional"`
	FinalPrice   float64 `json:"final_price,optional"`
	CancelReason string  `json:"cancel_reason,optional"`
}

type OrderListItem struct {
	OrderId        string  `json:"order_id"`
	PassengerName  string  `json:"passenger_name"`
	PassengerPhone string  `json:"passenger_phone"`
	DriverName     string  `json:"driver_name"`
	DriverPhone    string  `json:"driver_phone"`
	CarType        string  `json:"car_type"`
	StartAddress   string  `json:"start_address"`
	EndAddress     string  `json:"end_address"`
	Status         int32   `json:"status"`
	EstimatedPrice float64 `json:"estimated_price"`
	FinalPrice     float64 `json:"final_price"`
	CreatedAt      int64   `json:"created_at"`
}
