// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: driver.proto

package driverclient

import (
	"context"

	"driver-srv/pb/driver"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptOrderReq              = driver.AcceptOrderReq
	AcceptOrderResp             = driver.AcceptOrderResp
	ArrivePassengerLocationReq  = driver.ArrivePassengerLocationReq
	ArrivePassengerLocationResp = driver.ArrivePassengerLocationResp
	CancelOrderReq              = driver.CancelOrderReq
	CancelOrderResp             = driver.CancelOrderResp
	CartAuthReq                 = driver.CartAuthReq
	CartAuthResp                = driver.CartAuthResp
	DriverAuthReq               = driver.DriverAuthReq
	DriverAuthResp              = driver.DriverAuthResp
	DriverIncomeDetailData      = driver.DriverIncomeDetailData
	DriverLoginReq              = driver.DriverLoginReq
	DriverLoginResp             = driver.DriverLoginResp
	DriverOfflineReq            = driver.DriverOfflineReq
	DriverOfflineResp           = driver.DriverOfflineResp
	DriverOnlineReq             = driver.DriverOnlineReq
	DriverOnlineResp            = driver.DriverOnlineResp
	DriverOrderDetailItem       = driver.DriverOrderDetailItem
	DriverOrderDetailReq        = driver.DriverOrderDetailReq
	DriverOrderDetailResp       = driver.DriverOrderDetailResp
	DriverOrderHistoryItem      = driver.DriverOrderHistoryItem
	DriverOrderHistoryReq       = driver.DriverOrderHistoryReq
	DriverOrderHistoryResp      = driver.DriverOrderHistoryResp
	DriverOrderListReq          = driver.DriverOrderListReq
	DriverOrderListResp         = driver.DriverOrderListResp
	DriverRegisterReq           = driver.DriverRegisterReq
	DriverRegisterResp          = driver.DriverRegisterResp
	GetDriverInfoReq            = driver.GetDriverInfoReq
	GetDriverInfoResp           = driver.GetDriverInfoResp
	Location                    = driver.Location
	OutLoginReq                 = driver.OutLoginReq
	OutLoginResp                = driver.OutLoginResp
	SendSmsReq                  = driver.SendSmsReq
	SendSmsResp                 = driver.SendSmsResp
	StartAcceptOrderReq         = driver.StartAcceptOrderReq
	StartAcceptOrderResp        = driver.StartAcceptOrderResp
	StartTripReq                = driver.StartTripReq
	StartTripResp               = driver.StartTripResp
	StatusDriverCertReq         = driver.StatusDriverCertReq
	StatusDriverCertResp        = driver.StatusDriverCertResp
	StopAcceptOrderReq          = driver.StopAcceptOrderReq
	StopAcceptOrderResp         = driver.StopAcceptOrderResp
	SubmitDriverCertReq         = driver.SubmitDriverCertReq
	SubmitDriverCertResp        = driver.SubmitDriverCertResp
	UpdateDriverInfoReq         = driver.UpdateDriverInfoReq
	UpdateDriverInfoResp        = driver.UpdateDriverInfoResp

	Driver interface {
		// 司机认证模块
		SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsResp, error)
		DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error)
		DriverAuth(ctx context.Context, in *DriverAuthReq, opts ...grpc.CallOption) (*DriverAuthResp, error)
		CartAuth(ctx context.Context, in *CartAuthReq, opts ...grpc.CallOption) (*CartAuthResp, error)
		OutLogin(ctx context.Context, in *OutLoginReq, opts ...grpc.CallOption) (*OutLoginResp, error)
		// 司机接单与订单模块
		AcceptOrder(ctx context.Context, in *AcceptOrderReq, opts ...grpc.CallOption) (*AcceptOrderResp, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
		ArrivePassengerLocation(ctx context.Context, in *ArrivePassengerLocationReq, opts ...grpc.CallOption) (*ArrivePassengerLocationResp, error)
		StartTrip(ctx context.Context, in *StartTripReq, opts ...grpc.CallOption) (*StartTripResp, error)
		DriverOrderDetail(ctx context.Context, in *DriverOrderDetailReq, opts ...grpc.CallOption) (*DriverOrderDetailResp, error)
		DriverOrderList(ctx context.Context, in *DriverOrderListReq, opts ...grpc.CallOption) (*DriverOrderListResp, error)
		DriverOrderHistory(ctx context.Context, in *DriverOrderHistoryReq, opts ...grpc.CallOption) (*DriverOrderHistoryResp, error)
		StartAcceptOrder(ctx context.Context, in *StartAcceptOrderReq, opts ...grpc.CallOption) (*StartAcceptOrderResp, error)
		StopAcceptOrder(ctx context.Context, in *StopAcceptOrderReq, opts ...grpc.CallOption) (*StopAcceptOrderResp, error)
		DriverOnline(ctx context.Context, in *DriverOnlineReq, opts ...grpc.CallOption) (*DriverOnlineResp, error)
		DriverOffline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error)
		// 司机信息模块
		DriverRegister(ctx context.Context, in *DriverRegisterReq, opts ...grpc.CallOption) (*DriverRegisterResp, error)
		GetDriverInfo(ctx context.Context, in *GetDriverInfoReq, opts ...grpc.CallOption) (*GetDriverInfoResp, error)
		UpdateDriverInfo(ctx context.Context, in *UpdateDriverInfoReq, opts ...grpc.CallOption) (*UpdateDriverInfoResp, error)
		SubmitDriverCert(ctx context.Context, in *SubmitDriverCertReq, opts ...grpc.CallOption) (*SubmitDriverCertResp, error)
		StatusDriverCert(ctx context.Context, in *StatusDriverCertReq, opts ...grpc.CallOption) (*StatusDriverCertResp, error)
	}

	defaultDriver struct {
		cli zrpc.Client
	}
)

func NewDriver(cli zrpc.Client) Driver {
	return &defaultDriver{
		cli: cli,
	}
}

// 司机认证模块
func (m *defaultDriver) SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.SendSms(ctx, in, opts...)
}

func (m *defaultDriver) DriverLogin(ctx context.Context, in *DriverLoginReq, opts ...grpc.CallOption) (*DriverLoginResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverLogin(ctx, in, opts...)
}

func (m *defaultDriver) DriverAuth(ctx context.Context, in *DriverAuthReq, opts ...grpc.CallOption) (*DriverAuthResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverAuth(ctx, in, opts...)
}

func (m *defaultDriver) CartAuth(ctx context.Context, in *CartAuthReq, opts ...grpc.CallOption) (*CartAuthResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.CartAuth(ctx, in, opts...)
}

func (m *defaultDriver) OutLogin(ctx context.Context, in *OutLoginReq, opts ...grpc.CallOption) (*OutLoginResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.OutLogin(ctx, in, opts...)
}

// 司机接单与订单模块
func (m *defaultDriver) AcceptOrder(ctx context.Context, in *AcceptOrderReq, opts ...grpc.CallOption) (*AcceptOrderResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.AcceptOrder(ctx, in, opts...)
}

func (m *defaultDriver) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultDriver) ArrivePassengerLocation(ctx context.Context, in *ArrivePassengerLocationReq, opts ...grpc.CallOption) (*ArrivePassengerLocationResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.ArrivePassengerLocation(ctx, in, opts...)
}

func (m *defaultDriver) StartTrip(ctx context.Context, in *StartTripReq, opts ...grpc.CallOption) (*StartTripResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.StartTrip(ctx, in, opts...)
}

func (m *defaultDriver) DriverOrderDetail(ctx context.Context, in *DriverOrderDetailReq, opts ...grpc.CallOption) (*DriverOrderDetailResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverOrderDetail(ctx, in, opts...)
}

func (m *defaultDriver) DriverOrderList(ctx context.Context, in *DriverOrderListReq, opts ...grpc.CallOption) (*DriverOrderListResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverOrderList(ctx, in, opts...)
}

func (m *defaultDriver) DriverOrderHistory(ctx context.Context, in *DriverOrderHistoryReq, opts ...grpc.CallOption) (*DriverOrderHistoryResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverOrderHistory(ctx, in, opts...)
}

func (m *defaultDriver) StartAcceptOrder(ctx context.Context, in *StartAcceptOrderReq, opts ...grpc.CallOption) (*StartAcceptOrderResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.StartAcceptOrder(ctx, in, opts...)
}

func (m *defaultDriver) StopAcceptOrder(ctx context.Context, in *StopAcceptOrderReq, opts ...grpc.CallOption) (*StopAcceptOrderResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.StopAcceptOrder(ctx, in, opts...)
}

func (m *defaultDriver) DriverOnline(ctx context.Context, in *DriverOnlineReq, opts ...grpc.CallOption) (*DriverOnlineResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverOnline(ctx, in, opts...)
}

func (m *defaultDriver) DriverOffline(ctx context.Context, in *DriverOfflineReq, opts ...grpc.CallOption) (*DriverOfflineResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverOffline(ctx, in, opts...)
}

// 司机信息模块
func (m *defaultDriver) DriverRegister(ctx context.Context, in *DriverRegisterReq, opts ...grpc.CallOption) (*DriverRegisterResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.DriverRegister(ctx, in, opts...)
}

func (m *defaultDriver) GetDriverInfo(ctx context.Context, in *GetDriverInfoReq, opts ...grpc.CallOption) (*GetDriverInfoResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.GetDriverInfo(ctx, in, opts...)
}

func (m *defaultDriver) UpdateDriverInfo(ctx context.Context, in *UpdateDriverInfoReq, opts ...grpc.CallOption) (*UpdateDriverInfoResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.UpdateDriverInfo(ctx, in, opts...)
}

func (m *defaultDriver) SubmitDriverCert(ctx context.Context, in *SubmitDriverCertReq, opts ...grpc.CallOption) (*SubmitDriverCertResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.SubmitDriverCert(ctx, in, opts...)
}

func (m *defaultDriver) StatusDriverCert(ctx context.Context, in *StatusDriverCertReq, opts ...grpc.CallOption) (*StatusDriverCertResp, error) {
	client := driver.NewDriverClient(m.cli.Conn())
	return client.StatusDriverCert(ctx, in, opts...)
}
