// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: driver.proto

package server

import (
	"context"

	"driver-srv/internal/logic"
	"driver-srv/internal/svc"
	"driver-srv/pb/driver"
)

type DriverServer struct {
	svcCtx *svc.ServiceContext
	driver.UnimplementedDriverServer
}

func NewDriverServer(svcCtx *svc.ServiceContext) *DriverServer {
	return &DriverServer{
		svcCtx: svcCtx,
	}
}

// 司机认证模块
func (s *DriverServer) SendSms(ctx context.Context, in *driver.SendSmsReq) (*driver.SendSmsResp, error) {
	l := logic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}

func (s *DriverServer) DriverLogin(ctx context.Context, in *driver.DriverLoginReq) (*driver.DriverLoginResp, error) {
	l := logic.NewDriverLoginLogic(ctx, s.svcCtx)
	return l.DriverLogin(in)
}

func (s *DriverServer) DriverAuth(ctx context.Context, in *driver.DriverAuthReq) (*driver.DriverAuthResp, error) {
	l := logic.NewDriverAuthLogic(ctx, s.svcCtx)
	return l.DriverAuth(in)
}

func (s *DriverServer) CartAuth(ctx context.Context, in *driver.CartAuthReq) (*driver.CartAuthResp, error) {
	l := logic.NewCartAuthLogic(ctx, s.svcCtx)
	return l.CartAuth(in)
}

func (s *DriverServer) OutLogin(ctx context.Context, in *driver.OutLoginReq) (*driver.OutLoginResp, error) {
	l := logic.NewOutLoginLogic(ctx, s.svcCtx)
	return l.OutLogin(in)
}

// 司机接单与订单模块
func (s *DriverServer) AcceptOrder(ctx context.Context, in *driver.AcceptOrderReq) (*driver.AcceptOrderResp, error) {
	l := logic.NewAcceptOrderLogic(ctx, s.svcCtx)
	return l.AcceptOrder(in)
}

func (s *DriverServer) CancelOrder(ctx context.Context, in *driver.CancelOrderReq) (*driver.CancelOrderResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *DriverServer) ArrivePassengerLocation(ctx context.Context, in *driver.ArrivePassengerLocationReq) (*driver.ArrivePassengerLocationResp, error) {
	l := logic.NewArrivePassengerLocationLogic(ctx, s.svcCtx)
	return l.ArrivePassengerLocation(in)
}

func (s *DriverServer) StartTrip(ctx context.Context, in *driver.StartTripReq) (*driver.StartTripResp, error) {
	l := logic.NewStartTripLogic(ctx, s.svcCtx)
	return l.StartTrip(in)
}

func (s *DriverServer) DriverOrderDetail(ctx context.Context, in *driver.DriverOrderDetailReq) (*driver.DriverOrderDetailResp, error) {
	l := logic.NewDriverOrderDetailLogic(ctx, s.svcCtx)
	return l.DriverOrderDetail(in)
}

func (s *DriverServer) DriverOrderList(ctx context.Context, in *driver.DriverOrderListReq) (*driver.DriverOrderListResp, error) {
	l := logic.NewDriverOrderListLogic(ctx, s.svcCtx)
	return l.DriverOrderList(in)
}

func (s *DriverServer) DriverOrderHistory(ctx context.Context, in *driver.DriverOrderHistoryReq) (*driver.DriverOrderHistoryResp, error) {
	l := logic.NewDriverOrderHistoryLogic(ctx, s.svcCtx)
	return l.DriverOrderHistory(in)
}

func (s *DriverServer) StartAcceptOrder(ctx context.Context, in *driver.StartAcceptOrderReq) (*driver.StartAcceptOrderResp, error) {
	l := logic.NewStartAcceptOrderLogic(ctx, s.svcCtx)
	return l.StartAcceptOrder(in)
}

func (s *DriverServer) StopAcceptOrder(ctx context.Context, in *driver.StopAcceptOrderReq) (*driver.StopAcceptOrderResp, error) {
	l := logic.NewStopAcceptOrderLogic(ctx, s.svcCtx)
	return l.StopAcceptOrder(in)
}

func (s *DriverServer) DriverOnline(ctx context.Context, in *driver.DriverOnlineReq) (*driver.DriverOnlineResp, error) {
	l := logic.NewDriverOnlineLogic(ctx, s.svcCtx)
	return l.DriverOnline(in)
}

func (s *DriverServer) DriverOffline(ctx context.Context, in *driver.DriverOfflineReq) (*driver.DriverOfflineResp, error) {
	l := logic.NewDriverOfflineLogic(ctx, s.svcCtx)
	return l.DriverOffline(in)
}

// 司机信息模块
func (s *DriverServer) DriverRegister(ctx context.Context, in *driver.DriverRegisterReq) (*driver.DriverRegisterResp, error) {
	l := logic.NewDriverRegisterLogic(ctx, s.svcCtx)
	return l.DriverRegister(in)
}

func (s *DriverServer) GetDriverInfo(ctx context.Context, in *driver.GetDriverInfoReq) (*driver.GetDriverInfoResp, error) {
	l := logic.NewGetDriverInfoLogic(ctx, s.svcCtx)
	return l.GetDriverInfo(in)
}

func (s *DriverServer) UpdateDriverInfo(ctx context.Context, in *driver.UpdateDriverInfoReq) (*driver.UpdateDriverInfoResp, error) {
	l := logic.NewUpdateDriverInfoLogic(ctx, s.svcCtx)
	return l.UpdateDriverInfo(in)
}

func (s *DriverServer) SubmitDriverCert(ctx context.Context, in *driver.SubmitDriverCertReq) (*driver.SubmitDriverCertResp, error) {
	l := logic.NewSubmitDriverCertLogic(ctx, s.svcCtx)
	return l.SubmitDriverCert(in)
}

func (s *DriverServer) StatusDriverCert(ctx context.Context, in *driver.StatusDriverCertReq) (*driver.StatusDriverCertResp, error) {
	l := logic.NewStatusDriverCertLogic(ctx, s.svcCtx)
	return l.StatusDriverCert(in)
}
